language: java
jdk:
- oraclejdk7
env:
  matrix: 
  global:
  - secure: UP1Zb+KoHmDYCQKVawLdzBFxYRjXYMMpDppdDZuGhPdTDLvNuq/nG5ER7kzmMhggKk2+LwC8u/zub3jfTUREGtPZ3sbqHmm+l+mP1wXt2gvsNL6L4WwV/z7CAMrXTCbSy1KlU6CjSKaz3nDFaaI0cwRaMxD/EnrSwwe+MLmLPqPmNuAc3QgmV/Z345ff0XojD75Yqyt27VsDIoUCJMwKvpbA8oai+MYVm15/NhYIJi/oZ+JagnrVVQffKsJcwZZ4n2/fHCkH1z/HEd4hSvDXCRrLoS4KbQnEZ0ODsSSQP/DP5N9xE+Vj2ufbuGgLBy1stv1uh3i1F1hW6AcsQltygpz3LDlFF5wIJi1UEdT1eNYlMqBFFSvoV+XjXJVh5Gb2i//d25PBT8IG6kB9v0mp/RfCqm1m9wnt56R1CQJQk9p/cGjsLAKqWCXQJP8joQPk3p37n10X6DI9XqbUv+T1fGYuF+Ix9DVXq9MWzL/dJmPkYPRztX6N+BfnAzoTe/m9KkPuwcctPafUfirybv/wAQ+dA2O+u32VgMSB0p6pKh69PPiB3cULQ23zMwfTCX/Tnwh1drF8QWjgI07hO+p20VYSb8ATCf8U9f9fv6sYq5bMAj2+pceMrlRpNpEK3Dhf0lMR9ZrSLyVPGQ25zPq3y/nVM8N3DqYLblQdVnL0+U0=
  - secure: i4Bu9z2RBfqSr5oeDlXQ6uWhGnZPv6IF0bUEsXZvXJs1dI5daUtWEEzYFiHoOWSvK2RdvErNkyyx84B+8yNZZVIbneMD9VjzCsupaJXnhVe6gr0W8/jFr4kMI6L5oN4gvTt8np/kKPA7AB5HM8O4ZDoV1PGLD7q4pazg406lLpqhH79BQQIvzlPlKB41kWCFKXa13XE2ZnDTV0MDB0FYFajpIUzXHKwqrY5G8cU0A5DJZrs6N6jmObyqXi9IwNAtva3qCWHYqET8rAmmdMOZ/coW/UY96HERHvsJsETwDs0DatN/ayC/bbiyuel4FqnfqsGucucNIBTKVKOj28en8T4EkaWP7bH3E9r8KUOYMn1W0wHj2RCT3d5ectWWGHb/juEunDui0j5VBi7lZqJV+HIwkFHFtoQdPhLBioEqCWS6a107kr6SAr7dTfaS7NxhMaYHYYWGRS+EA/FN+VCRDen7UCXrkufTYIwnxwMYacNnGEun7s2+v3/C1N0WG9Hly7D9tHBiV7I9rcj2AC+MFpYHMzWe0Y5TgdMCNx4rJnVXCK7UvBI64SHEhZ6Y9XWjoPHiG+eZ9XEXMa9BAGrTAu0rz0Q5ocJaAWAPU1OTgKJMpCmGjQuMLb74rnCwd7rIF0e6l9qXCE31gTWqLL0+CUy1kSE4zVY+2bLLnTRN/jI=
script: mvn clean package
notifications:
  email:
    recipients: paul.t.oconnell@gmail.com
